[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/h00pz"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://www.linkedin.com/in/mark-hooper-8837b64/"

    [social.params]
        icon = "brand-linkedin"
